### ISSUE TITLE
No spoken response when running via Siri / Shortcuts app

### ISSUE THREAD

**Issue by bfg100k** [thoukydides/siri-squeezebox-control#2] opened 2021-04-30 00:43 UTC
Hi, thanks for creating this useful script. I managed to get it working with Siri following your instructions. (i.e. commands do get relayed to my Squeezebox player) However, I do not get a spoken response at all (like "Sorry, I don't know how to..."). I tested in Shortcuts app directly and I don't get the spoken response too. Testing in Scriptable, I do get the spoken response although it is in a male voice (my siri setting is female). Any ideas what could be wrong?

UPDATE: After some more troubleshooting, managed to get a workaround going. Here's my findings and workaround solution in case anyone else have the same issue.

1) Scriptable app uses Voiceover function in iOS for the text to speech (hence the male voice in my case as that is the default for Accessibility -> Voiceover)
2) I create a simple script in Scriptable to test the Speech.speak API in the shortcuts app. No luck there so I now suspect the issue is with the Scriptable app rather than your script.
3) Googling online, found a release note saying the Speech.speak API does not work in Siri for some languages. (https://talk.automators.fm/t/release-notes-for-scriptable/1611/4). I use English(Australia). Not sure if that is the cause.
4) As a workaround, instead of using the Speech.speak API, I changed it to Script.setShortcutOutput(Response) to pass the message back to the Shortcut app. Then in the Shortcut app, I added another action to speak the output from Scriptable.

**Comment by thoukydides** [comment] 2021-04-30 08:16
Thank you for reporting this issue, and especially for investigating/fixing it yourself.

> However, I do not get a spoken response at all (like "Sorry, I don't know how to..."). I tested in Shortcuts app directly and I don't get the spoken response too.

I have seen similar problems in the past, usually soon after new iOS releases where the behaviour of Siri, Shortcuts, or in-app intent, etc, have changed subtly. However, it all works correctly for me with iOS 14.5 and Scriptable 1.6.3.

> 1. Scriptable app uses Voiceover function in iOS for the text to speech (hence the male voice in my case as that is the default for Accessibility -> Voiceover)

You can configure VoiceOver to use the Siri voice.

> 2. I create a simple script in Scriptable to test the Speech.speak API in the shortcuts app. No luck there so I now suspect the issue is with the Scriptable app rather than your script.
> 3. Googling online, found a release note saying the Speech.speak API does not work in Siri for some languages. (https://talk.automators.fm/t/release-notes-for-scriptable/1611/4). I use English(Australia). Not sure if that is the cause.

In my case I am using British Voice 1. However, it still works if I change it to Australian Voice 2...

The release note that you link to claim that the issue is fixed in Scriptable build 16. If it doesn't work for you then I suggest you report it to the author (at mail@scriptable.app or via the Automators forum).

> 4. As a workaround, instead of using the Speech.speak API, I changed it to Script.setShortcutOutput(Response) to pass the message back to the Shortcut app. Then in the Shortcut app, I added another action to speak the output from Scriptable.

Good to hear that you found a solution. Hopefully it will help anyone else having similar issues.

However, I don't currently intend to adopt that change since the current implementation works fine for me, and I prefer to keep the Shortcuts as simple as possible...

**Closed as completed by thoukydides** 2021-04-30 08:16 UTC
